# Generated by Django 4.0.6 on 2022-07-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ur_login', models.CharField(max_length=20, null=True)),
                ('ur_fio', models.TextField()),
                ('ur_password', models.CharField(max_length=20, null=True)),
                ('ur_private', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_fio', models.TextField()),
                ('em_phone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=100, null=True)),
                ('pr_start', models.DateField(null=True)),
                ('pr_end', models.DateField(null=True)),
                ('pr_stage', models.CharField(max_length=150, null=True)),
                ('pr_price', models.PositiveIntegerField(default=1000)),
                ('pr_discription', models.TextField(null=True)),
                ('pr_type', models.PositiveIntegerField(default=1)),
                ('pr_buyer', models.ManyToManyField(related_name='Client', to='api.client')),
                ('pr_emloyee', models.ManyToManyField(related_name='Employee', to='api.employee')),
            ],
        ),
    ]
