# Generated by Django 4.0.6 on 2022-07-15 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='project',
            name='pr_buyer',
            field=models.ManyToManyField(related_name='UserAccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
