# Generated by Django 4.0.6 on 2022-07-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
